kumuluzee:
  name: upload-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://image-upload:8080
    http:
      port: 8080
  health:
    servlet:
      mapping: /health
      enabled: true
    logs:
      enabled: true
      level: INFO
      period-s: 30
    checks:
        mongo-health-check:
          connection-url:  mongodb+srv://pastafarian:goldi1@cluster0-mtykz.gcp.mongodb.net/test?retryWrites=true&w=majority
          type: liveness
        disk-space-health-check:
          threshold: 100000000